# CNN3H SAC Config

sac_hyperparams:
  learning_rate: 0.0003
  batch_size: 256
  gamma: 0.99
  tau: 0.005
  ent_coef: 'auto'
  train_freq: 1
  gradient_steps: 1
  learning_starts: 5000

model:
  np_steps: 10   # number of past steps (length of time history)
  nf_steps: 5    # number of future predicted steps
