policy_type: cnn  # "cnn" or "mlp"

policy_kwargs:
  features_extractor_kwargs:
    conv_layers: [32, 64]
    kernel_size: 3
    activation: relu
  net_arch: [256, 256]

sac_hyperparams:
  learning_rate: 0.0003
  batch_size: 256
  gamma: 0.99
  tau: 0.005
  ent_coef: auto
  train_freq: 1
  gradient_steps: 1
  learning_starts: 1000
